package uz.jbnuu.tsc.model.student

data class StudentData(
    val id: Int?,// 856,
    val auth_id: String?,// "401201100008",
    val familya: String?,// "MAXMUDOVA",
    val ism: String?,// "MUNIRA",
    val otasi_ismi: String?,// "QUVONDIQQIZI",
    val passport: String?,// "AC2139061",
    val JSHSHIR: String?,// "60906035430024",
    val fuqarolik: String?,// "O‘zbekiston Respublikasi fuqarosi",
    val davlat: String?,// "O‘zbekiston",
    val millat: String?,// "O‘zbeklar",
    val viloyat: String?,// "Jizzax viloyati",
    val tuman: String?,// "Baxmal tumani",
    val jins: String?,// "Ayol",
    val tugilgan_sana: String?,// "2003-06-09",
    val group_id: Int?,// 38,
    val education_type: String?,// "Bakalavr",
    val education_shape: String?,// "Kunduzgi",
    val education_grand: String?,// "Davlat granti",
    val old_education: String?,// "2018-2020, Jizzax Politexnika instituti akademik litseyi L №  0001818",
    val student_type: String?,// "Oddiy",
    val social_type: String?,// "Boshqa",
    val count_with_person_life: String?,// "5",
    val type_with_person_life: String?,// "Boshqa OTM talabalari",
    val adress_status: String?,// "Sariq hudud",
    val adress: String?,// "---",
    val geo_adress: String?,// "---",
    val email: String?,// "AC2139061@gmail.com",
    val email_verified_at: String?,// null,
    val password: String?,// "$2y$10$wL4n3UPF4.cIcAxs7.mr0.ZU37hK8.rGkL0CEQvrSGNKJLotVXoca",
    val last_location: String?,// "{\"lat\": \"41.12582334514015\", \"long\": \"67.88733816241829\", \"data_time\": \"2022-08-02 09:30:10\"}",
    val token: String?,// "abb190fc793564e83c94c4f13e0d7a77",
    val role_id: Int?,// 4,
)
